Repository 5Iridescent/AllDay-Fit, pull requests merged in 2023-10, with the labels that each got.

#1 [desgin] 컬러 추가
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: enhancement, desgin

#2 UI/calendar
  app/src/main/java/com/example/alldayfit/CalendarFragment.kt
  app/src/main/res/layout/calendar_fragment.xml
Labels: desgin

#6 [TSK-19] Community UI Design
  app/build.gradle.kts
  app/src/main/java/com/example/alldayfit/CommunityHomeFragment.kt
  app/src/main/java/com/example/alldayfit/MainActivity.kt
  app/src/main/res/drawable/button_radius.xml
  app/src/main/res/drawable/button_radius2.xml
  app/src/main/res/drawable/dialog_radius.xml
  app/src/main/res/drawable/exercise_record_board.xml
  app/src/main/res/drawable/ic_add.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_calendar.xml
  app/src/main/res/drawable/ic_camera.xml
  app/src/main/res/drawable/ic_circle.xml
  app/src/main/res/drawable/ic_circle_check.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_commity.xml
  app/src/main/res/drawable/ic_diet.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_main.xml
  app/src/main/res/drawable/ic_menu.xml
  app/src/main/res/drawable/ic_mypage.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/drawable/ic_plus_color.xml
  app/src/main/res/drawable/ic_trash.xml
  app/src/main/res/drawable/ic_user.xml
  app/src/main/res/drawable/ic_user2.xml
  app/src/main/res/drawable/ic_weight.xml
  app/src/main/res/drawable/main_btn.xml
  app/src/main/res/drawable/menu_click_color.xml
  app/src/main/res/drawable/tab_background.xml
  app/src/main/res/drawable/tab_background_activated.xml
  app/src/main/res/drawable/user_cond_board.xml
  app/src/main/res/layout/commnunity_main.xml
  app/src/main/res/layout/commnunity_mypost_fragment.xml
  app/src/main/res/layout/community_home_fragment.xml
  app/src/main/res/layout/community_items.xml
  app/src/main/res/layout/community_newpost.xml
  app/src/main/res/layout/community_post.xml
  app/src/main/res/layout/main_activity.xml
  app/src/main/res/menu/main_bottomappbar_menu.xml
  app/src/main/res/menu/main_toolbar_menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: desgin

#7 [Design] Calendar
  app/src/main/java/com/example/alldayfit/CalendarActivity.kt
  app/src/main/java/com/example/alldayfit/CalendarFragment.kt
  app/src/main/res/drawable/cancel.png
  app/src/main/res/drawable/ic_chevron_left.xml
  app/src/main/res/drawable/ic_chevron_right.xml
  app/src/main/res/layout/calendar_activity.xml
  app/src/main/res/layout/calendar_day.xml
  app/src/main/res/layout/calendar_day_legend_container.xml
  app/src/main/res/layout/calendar_day_legend_text.xml
  app/src/main/res/layout/calendar_fragment.xml
  app/src/main/res/layout/calendar_header.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: desgin

#8 [TSK-19] 커뮤니티 UI 수정
  app/src/main/res/layout/commnunity_main.xml
  app/src/main/res/layout/commnunity_mypost_fragment.xml
  app/src/main/res/layout/community_home_fragment.xml
Labels: fix

#9 [FEAT] setting xml modify
  app/build.gradle.kts
  app/src/main/java/com/example/alldayfit/Settings/SettingAppNotifiFragment.kt
  app/src/main/java/com/example/alldayfit/Settings/SettingGuideFragment.kt
  app/src/main/java/com/example/alldayfit/Settings/SettingMainFragment.kt
  app/src/main/java/com/example/alldayfit/Settings/SettingModUserFragment.kt
  app/src/main/java/com/example/alldayfit/Settings/SettingNoticeAdapter.kt
  app/src/main/java/com/example/alldayfit/Settings/SettingNoticeFragment.kt
  app/src/main/java/com/example/alldayfit/Settings/SettingNoticeItem.kt
  app/src/main/res/drawable/app_notifi_setting.png
  app/src/main/res/drawable/camera.png
  app/src/main/res/drawable/darkmode.png
  app/src/main/res/drawable/guide.png
  app/src/main/res/drawable/mod_user_info.png
  app/src/main/res/drawable/modify.png
  app/src/main/res/drawable/notice.png
  app/src/main/res/layout/setting_guide_fragment.xml
  app/src/main/res/layout/setting_main_fragment.xml
  app/src/main/res/layout/setting_mod_user_fragment.xml
  app/src/main/res/layout/setting_notice_fragment.xml
  app/src/main/res/layout/setting_notice_item.xml
  app/src/main/res/layout/setting_notifi_fragment.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/xml/root_preferences.xml
Labels: fix

#11 [TSK-19] Fix/community page
  app/src/main/res/layout/commnunity_main.xml
  app/src/main/res/layout/community_items.xml
  app/src/main/res/layout/community_newpost.xml
  app/src/main/res/layout/community_post.xml
  app/src/main/res/values/strings.xml
Labels: fix

#12 [TSK-22] 식단기록/운동기록 page
  app/src/main/java/com/example/alldayfit/MainActivity.kt
  app/src/main/java/com/example/alldayfit/Settings/SettingMainFragment.kt
  app/src/main/java/com/example/alldayfit/Settings/SettingNoticeItem.kt
  app/src/main/java/com/example/alldayfit/calendar/CalendarActivity.kt
  app/src/main/java/com/example/alldayfit/calendar/CalendarFragment.kt
  app/src/main/java/com/example/alldayfit/community/CommunityHomeFragment.kt
  app/src/main/java/com/example/alldayfit/dietrecord/DietRecordFragment.kt
  app/src/main/java/com/example/alldayfit/exercisestatus/ExerciseStatusDailyEditDialog.java
  app/src/main/java/com/example/alldayfit/exercisestatus/ExerciseStatusFragment.kt
  app/src/main/java/com/example/alldayfit/main/MainFragment.kt
  app/src/main/java/com/example/alldayfit/settings/adapter/SettingNoticeAdapter.kt
  app/src/main/java/com/example/alldayfit/settings/ui/SettingAppNotifiFragment.kt
  app/src/main/java/com/example/alldayfit/settings/ui/SettingGuideFragment.kt
  app/src/main/java/com/example/alldayfit/settings/ui/SettingMainFragment.kt
  app/src/main/java/com/example/alldayfit/settings/ui/SettingModUserFragment.kt
  app/src/main/java/com/example/alldayfit/settings/ui/SettingNoticeFragment.kt
  app/src/main/java/com/example/alldayfit/settings/ui/SettingNoticeItem.kt
  app/src/main/res/drawable/exercise_status_fix_btn_shape.xml
  app/src/main/res/drawable/exercise_status_user_item_shape.xml
  app/src/main/res/drawable/exercise_week_goal_shape.xml
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/drawable/ic_next.xml
  app/src/main/res/drawable/ic_prev.xml
  app/src/main/res/drawable/view_corner_5.xml
  app/src/main/res/layout/calendar_activity.xml
  app/src/main/res/layout/calendar_day_legend_container.xml
  app/src/main/res/layout/calendar_fragment.xml
  app/src/main/res/layout/calendar_header.xml
  app/src/main/res/layout/commnunity_main.xml
  app/src/main/res/layout/community_home_fragment.xml
  app/src/main/res/layout/community_newpost.xml
  app/src/main/res/layout/diet_record_fragment.xml
  app/src/main/res/layout/diet_record_meal_item.xml
  app/src/main/res/layout/diet_record_nutritional_analysis_item.xml
  app/src/main/res/layout/exercise_status_daily_edit_dialog.xml
  app/src/main/res/layout/exercise_status_fragment.xml
  app/src/main/res/layout/exercise_status_goal_item.xml
  app/src/main/res/layout/exercise_status_user_item.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/main_activity.xml
  app/src/main/res/layout/setting_guide_fragment.xml
  app/src/main/res/layout/setting_main_fragment.xml
  app/src/main/res/layout/setting_mod_user_fragment.xml
  app/src/main/res/layout/setting_notice_fragment.xml
  app/src/main/res/layout/setting_notice_item.xml
  app/src/main/res/layout/setting_notifi_fragment.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: enhancement, desgin

#13 [TSK-20] settings 화면 수정
  app/src/main/res/layout/setting_guide_fragment.xml
  app/src/main/res/layout/setting_main_fragment.xml
  app/src/main/res/layout/setting_mod_user_fragment.xml
  app/src/main/res/layout/setting_notice_fragment.xml
  app/src/main/res/layout/setting_notice_item.xml
  app/src/main/res/layout/setting_notifi_fragment.xml
  app/src/main/res/values/strings.xml
Labels: fix

#15 [fix] string 중복 제거
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/strings.xml
Labels: fix

#20 환경설정 고정 strings.xml 중복 제거 및 name 수정
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/strings.xml
Labels: fix

#21 [Fix] calendar 코드 충돌
  app/src/main/java/com/example/alldayfit/calendar/CalendarFragment.kt
  app/src/main/res/layout/calendar_fragment.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug, fix

#24 [Feature] Room DB 기본 설정
  app/build.gradle.kts
  app/src/main/java/com/example/alldayfit/database/dao/DAO.kt
  app/src/main/java/com/example/alldayfit/database/data/AlldayFit_Data.kt
  app/src/main/java/com/example/alldayfit/database/entity/Entity.kt
  build.gradle.kts
Labels: enhancement

#22 [TSK-31] 식단 기록 추가/삭제 기능 구현
  app/src/main/java/com/example/alldayfit/dietrecord/DietRecord.kt
  app/src/main/java/com/example/alldayfit/dietrecord/DietRecordAdapter.kt
  app/src/main/java/com/example/alldayfit/dietrecord/DietRecordFragment.kt
  app/src/main/res/layout/diet_record_add_dialog.xml
  app/src/main/res/layout/diet_record_add_item.xml
  app/src/main/res/layout/diet_record_meal_item.xml
Labels: enhancement

#25 [TSK-38] 운동 시작/완료 시간 및 총 운동 시간 계산
  app/src/main/java/com/example/alldayfit/main/MainFragment.kt
Labels: enhancement

#28 [TSK-40] 식단 기록 이미지 추가 기능 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/alldayfit/dietrecord/DietRecord.kt
  app/src/main/java/com/example/alldayfit/dietrecord/DietRecordFragment.kt
  app/src/main/java/com/example/alldayfit/main/MainFragment.kt
  app/src/main/res/layout/diet_record_add_dialog.xml
Labels: enhancement

#30 [TSK-45] 식단 기록 - 하루 섭취 영양 차트로 표시(더미데이터 생성)
  app/src/main/java/com/example/alldayfit/dietrecord/DietRecordFragment.kt
  app/src/main/res/layout/diet_record_fragment.xml
Labels: fix

#31 [Feature] status item
  app/src/main/java/com/example/alldayfit/database/dao/DAO.kt
  app/src/main/java/com/example/alldayfit/database/data/AlldayFit_Data.kt
  app/src/main/java/com/example/alldayfit/database/entity/Entity.kt
  app/src/main/java/com/example/alldayfit/exercisestatus/BodyStatusDialog.kt
  app/src/main/java/com/example/alldayfit/exercisestatus/BodyStatusEdit.kt
  app/src/main/java/com/example/alldayfit/exercisestatus/BodyStatusViewModel.kt
  app/src/main/java/com/example/alldayfit/exercisestatus/ExerciseStatusFragment.kt
  app/src/main/res/layout/exercise_status_daily_edit_dialog.xml
  app/src/main/res/layout/exercise_status_fragment.xml
  app/src/main/res/layout/exercise_status_user_input_item.xml
Labels: enhancement, desgin, fix

#29 [TSK-40] 식단 이미지 추가 코드 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/alldayfit/dietrecord/DietRecordFragment.kt
  app/src/main/res/layout/diet_record_add_dialog.xml
Labels: fix

#33 [TSK-40]식단 기록 다이얼로그 강제종료 에러 해결
  app/src/main/java/com/example/alldayfit/dietrecord/DietRecordFragment.kt
Labels: fix

#32 [Ddsign]countpage TSK-63
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/alldayfit/count/Count.kt
  app/src/main/java/com/example/alldayfit/count/CountDialog.kt
  app/src/main/java/com/example/alldayfit/count/CountPage.kt
  app/src/main/java/com/example/alldayfit/count/CountViewmodel.kt
  app/src/main/java/com/example/alldayfit/main/MainFragment.kt
  app/src/main/res/drawable/btn_counter.xml
  app/src/main/res/drawable/btn_counter2.xml
  app/src/main/res/drawable/circle_blue_back_shape.xml
  app/src/main/res/drawable/circle_orange_back_shape.xml
  app/src/main/res/drawable/count_spinner_item.xml
  app/src/main/res/drawable/ic_arrrow_down.xml
  app/src/main/res/drawable/ic_close_black.xml
  app/src/main/res/drawable/item_radius.xml
  app/src/main/res/layout/activity_count_page.xml
  app/src/main/res/layout/count_add_dialog.xml
  app/src/main/res/layout/count_item.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/strings.xml
Labels: desgin

#35 [fix] 누락된 코드 추가
  app/src/main/java/com/example/alldayfit/dietrecord/DietRecordFragment.kt
Labels: fix
