Repository 5Iridescent/AllDay-Fit, pull requests merged in 2023-11, with the labels that each got.

#39 [TSK-75] 타이머 기능 구현
  app/src/main/java/com/example/alldayfit/count/CountPage.kt
  app/src/main/res/drawable/circle_blue_back_shape.xml
  app/src/main/res/layout/count_page_activity.xml
  app/src/main/res/layout/diet_record_fragment.xml
Labels: enhancement, fix

#38 [REFACTOR] mainfragment
  app/src/main/java/com/example/alldayfit/community/CommunityNewPostDialog.kt
  app/src/main/java/com/example/alldayfit/community/CommunityViewModel.kt
  app/src/main/java/com/example/alldayfit/exercisestatus/BodyStatusViewModel.kt
  app/src/main/java/com/example/alldayfit/exercisestatus/ExerciseStatusFragment.kt
  app/src/main/java/com/example/alldayfit/exercisestatus/ExerciseStatusViewModel.kt
  app/src/main/java/com/example/alldayfit/main/ExerciseStatusAddGoalDialog.kt
  app/src/main/java/com/example/alldayfit/main/Goal.kt
  app/src/main/java/com/example/alldayfit/main/MainFragment.kt
  app/src/main/java/com/example/alldayfit/main/MainViewModel.kt
  app/src/main/java/com/example/alldayfit/main/adapter/GoalAdapter.kt
  app/src/main/res/layout/diet_record_add_dialog.xml
  app/src/main/res/layout/diet_record_add_item.xml
  app/src/main/res/layout/main_add_goal_dialog.xml
  app/src/main/res/layout/main_goal_item.xml
  app/src/main/res/navigation/main_graph.xml
Labels: desgin, fix

#40 [TSK-76] 신체 정보 수정 다이얼로그 디자인 수정
  app/src/main/res/layout/exercise_status_daily_edit_dialog.xml
Labels: desgin, fix

#41 [TSK-77] main화면 수정
  app/src/main/java/com/example/alldayfit/MainActivity.kt
  app/src/main/java/com/example/alldayfit/community/CommunityViewModel.kt
  app/src/main/java/com/example/alldayfit/community/adapter/CommunityViewAdapter.kt
  app/src/main/java/com/example/alldayfit/db/RealTimeRepository.kt
  app/src/main/java/com/example/alldayfit/db/RealTimeRepositoryImpl.kt
  app/src/main/java/com/example/alldayfit/db/model/FirebaseModel.kt
  app/src/main/java/com/example/alldayfit/dietrecord/DietRecordAddDialog.kt
  app/src/main/java/com/example/alldayfit/dietrecord/DietRecordFragment.kt
  app/src/main/java/com/example/alldayfit/dietrecord/DietRecordViewModel.kt
  app/src/main/java/com/example/alldayfit/dietrecord/DietRecordViewModelFactory.kt
  app/src/main/java/com/example/alldayfit/exercisestatus/BodyStatusDialog.kt
  app/src/main/java/com/example/alldayfit/exercisestatus/ExerciseStatusFragment.kt
  app/src/main/java/com/example/alldayfit/main/ExerciseStatusAddGoalDialog.kt
  app/src/main/java/com/example/alldayfit/main/MainFragment.kt
  app/src/main/java/com/example/alldayfit/main/MainViewModel.kt
  app/src/main/java/com/example/alldayfit/main/MainViewModelFactory.kt
  app/src/main/java/com/example/alldayfit/main/adapter/GoalAdapter.kt
  app/src/main/java/com/example/alldayfit/main/model/Goal.kt
  app/src/main/java/com/example/alldayfit/settings/ui/SettingAppNotifiFragment.kt
  app/src/main/java/com/example/alldayfit/settings/ui/SettingMainFragment.kt
  app/src/main/res/layout/main_add_goal_dialog.xml
  app/src/main/res/layout/main_fragment.xml
  app/src/main/res/layout/main_goal_item.xml
  app/src/main/res/layout/main_weekly_record_item.xml
  app/src/main/res/navigation/main_graph.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: enhancement, desgin

#43 [TSK-75] 타이머 중간 기록 구현
  app/src/main/java/com/example/alldayfit/count/CountPage.kt
  app/src/main/java/com/example/alldayfit/count/ExerciseRecord.kt
  app/src/main/java/com/example/alldayfit/count/ExerciseRecordAdapter.kt
  app/src/main/res/drawable/circle_blue_back_shape.xml
  app/src/main/res/drawable/circle_orange_back_shape.xml
  app/src/main/res/drawable/item_radius.xml
  app/src/main/res/layout/count_item.xml
  app/src/main/res/layout/count_page_activity.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, fix

#45 [feature] community realtime crud
  app/src/main/java/com/example/alldayfit/community/model/CommunityPostEntity.kt
  app/src/main/java/com/example/alldayfit/db/RealTimeRepository.kt
  app/src/main/java/com/example/alldayfit/db/RealTimeRepositoryImpl.kt
  app/src/main/java/com/example/alldayfit/db/model/FirebaseModel.kt
Labels: enhancement, fix

#44 [DESIGN]TSK-77
  app/src/main/java/com/example/alldayfit/community/CommunityHomeFragment.kt
  app/src/main/java/com/example/alldayfit/community/CommunityNewPostDialog.kt
  app/src/main/java/com/example/alldayfit/community/CommunityViewModel.kt
  app/src/main/java/com/example/alldayfit/exercisestatus/BodyStatusDialog.kt
  app/src/main/java/com/example/alldayfit/exercisestatus/ExerciseStatusDailyEditDialog.kt
  app/src/main/java/com/example/alldayfit/exercisestatus/ExerciseStatusFragment.kt
  app/src/main/res/drawable/gray_stroke_white_back_shape.xml
  app/src/main/res/drawable/ic_star.xml
  app/src/main/res/layout/exercise_status_fragment.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/strings.xml
Labels: desgin

#47 [TSK-82] user상태&식단기록 MVVM 작업
  app/src/main/java/com/example/alldayfit/db/RealTimeRepositoryImpl.kt
  app/src/main/java/com/example/alldayfit/dietrecord/DietRecordAddDialog.kt
  app/src/main/java/com/example/alldayfit/dietrecord/DietRecordDialogViewModel.kt
  app/src/main/java/com/example/alldayfit/dietrecord/DietRecordDialogViewModelFactory.kt
  app/src/main/java/com/example/alldayfit/dietrecord/DietRecordFragment.kt
  app/src/main/java/com/example/alldayfit/dietrecord/DietRecordViewModel.kt
  app/src/main/java/com/example/alldayfit/dietrecord/model/DietRecordModel.kt
  app/src/main/java/com/example/alldayfit/exercisestatus/BodyStatusDialog.kt
  app/src/main/java/com/example/alldayfit/exercisestatus/BodyStatusEdit.kt
  app/src/main/java/com/example/alldayfit/exercisestatus/BodyStatusViewModel.kt
  app/src/main/java/com/example/alldayfit/exercisestatus/ExerciseBodyStatusEditDialog.kt
  app/src/main/java/com/example/alldayfit/exercisestatus/ExerciseStatusDailyEditDialog.kt
  app/src/main/java/com/example/alldayfit/exercisestatus/ExerciseStatusFragment.kt
  app/src/main/java/com/example/alldayfit/exercisestatus/model/BodyStatusEdit.kt
  app/src/main/java/com/example/alldayfit/main/MainFragment.kt
  app/src/main/java/com/example/alldayfit/main/MainViewModel.kt
  app/src/main/java/com/example/alldayfit/main/MainViewModelFactory.kt
  app/src/main/res/layout/exercise_status_daily_edit_dialog.xml
  app/src/main/res/navigation/main_graph.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, desgin, fix

#48 [BUG_FIX] : 🐛 서명 추가&최신 버전 적용& google-services 교체
  .gitignore
  app/build.gradle.kts
  app/src/google-services.json
  app/src/main/java/com/example/alldayfit/dietrecord/DietRecordAddDialog.kt
  build.gradle.kts
Labels: fix

#50 [TSK-75] 프로그래스바 구현
  app/src/main/java/com/example/alldayfit/count/CountPage.kt
  app/src/main/res/drawable/progress_circular.xml
  app/src/main/res/layout/activity_count_page.xml
  app/src/main/res/layout/count_page_activity.xml
  app/src/main/res/values/styles.xml
Labels: enhancement, fix

#52 [TSK-79] FoodLens 사용 설정 및 구현 부분 추가
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/alldayfit/dietrecord/DietRecordAddDialog.kt
  app/src/main/java/com/example/alldayfit/dietrecord/Utils.kt
  app/src/main/res/values/strings.xml
Labels: fix

#53 [Feature] ui text style 적용
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/alldayfit/MainActivity.kt
  app/src/main/java/com/example/alldayfit/db/RealTimeRepository.kt
  app/src/main/java/com/example/alldayfit/db/RealTimeRepositoryImpl.kt
  app/src/main/java/com/example/alldayfit/dietrecord/DietRecordAddDialog.kt
  app/src/main/java/com/example/alldayfit/dietrecord/DietRecordViewModel.kt
  app/src/main/java/com/example/alldayfit/dietrecord/DietRecordViewModelFactory.kt
  app/src/main/java/com/example/alldayfit/dietrecord/Utils.kt
  app/src/main/java/com/example/alldayfit/main/ExerciseStatusAddGoalDialog.kt
  app/src/main/java/com/example/alldayfit/main/MainFragment.kt
  app/src/main/java/com/example/alldayfit/main/MainViewModel.kt
  app/src/main/java/com/example/alldayfit/main/MainViewModelFactory.kt
  app/src/main/java/com/example/alldayfit/main/adapter/GoalAdapter.kt
  app/src/main/java/com/example/alldayfit/main/model/DailyExercise.kt
  app/src/main/java/com/example/alldayfit/main/model/Goal.kt
  app/src/main/res/drawable/btn_exercise.xml
  app/src/main/res/drawable/ic_circle.xml
  app/src/main/res/layout/community_items.xml
  app/src/main/res/layout/community_main_fragment.xml
  app/src/main/res/layout/community_newpost_dialog.xml
  app/src/main/res/layout/diet_record_add_item.xml
  app/src/main/res/layout/diet_record_meal_item.xml
  app/src/main/res/layout/exercise_status_fragment.xml
  app/src/main/res/layout/exercise_status_user_item.xml
  app/src/main/res/layout/main_activity.xml
  app/src/main/res/layout/main_add_goal_dialog.xml
  app/src/main/res/layout/main_fragment.xml
  app/src/main/res/layout/main_weekly_record_item.xml
  app/src/main/res/layout/setting_guide_fragment.xml
  app/src/main/res/layout/setting_main_fragment.xml
  app/src/main/res/layout/setting_mod_user_fragment.xml
  app/src/main/res/layout/setting_notice_fragment.xml
  app/src/main/res/layout/setting_notice_item.xml
  app/src/main/res/layout/setting_notifi_fragment.xml
  app/src/main/res/navigation/main_graph.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: enhancement, desgin

#57 [Fix] ui text style 적용
  app/src/main/java/com/example/alldayfit/main/ExerciseStatusAddGoalDialog.kt
  app/src/main/java/com/example/alldayfit/main/adapter/GoalAdapter.kt
Labels: fix

#60 [TSK-81][Feature] : 이메일 회원가입/로그인 기능 구현
  app/src/main/java/com/example/alldayfit/settings/EmailSignUpActivity.kt
  app/src/main/java/com/example/alldayfit/settings/GoogleSignInPage.kt
  app/src/main/res/drawable/btn_google.xml
  app/src/main/res/drawable/round_button.xml
  app/src/main/res/layout/email_sign_up_activity.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, desgin

#62 Hot fix/login
  app/src/main/res/layout/sign_in_page_activity.xml
Labels: fix

#66 [Feature]splash screen
  app/build.gradle.kts
  app/src/main/java/com/example/alldayfit/calendar/BaseFragment.kt
  app/src/main/java/com/example/alldayfit/calendar/CalendarActivity.kt
  app/src/main/java/com/example/alldayfit/calendar/CalendarFragment.kt
  app/src/main/java/com/example/alldayfit/calendar/adapter/CalendarOptionadapater.kt
  app/src/main/java/com/example/alldayfit/calendar/anim/Animation.kt
  app/src/main/java/com/example/alldayfit/calendar/data/CalendarData.kt
  app/src/main/java/com/example/alldayfit/calendar/util/Util.kt
  app/src/main/java/com/example/alldayfit/utils/SplashActivity.kt
  app/src/main/res/drawable/logo_transparent.xml
  app/src/main/res/drawable/sky_blue_solid_shape.xml
  app/src/main/res/layout/email_sign_up_activity.xml
  app/src/main/res/layout/sign_in_page_activity.xml
  app/src/main/res/navigation/main_graph.xml
  app/src/main/res/values-v31/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: enhancement
